Fix: added command name validation. 	modified:   etckeeper

diff --git a/etckeeper b/etckeeper
--- a/etckeeper
+++ b/etckeeper
@@ -75,6 +75,10 @@ elif [ "$command" = "pre-apt" ]; then
 	command=pre-install
 fi
 
+(echo "$command" | egrep '\.\./') >/dev/null && (
+	echo "etckeeper: invalid command $command" >&2
+	exit 2
+)
 if [ ! -d "$ETCKEEPER_CONF_DIR/$command.d" ]; then
 	echo "etckeeper: $ETCKEEPER_CONF_DIR/$command.d does not exist" >&2
 	exit 1
